import type { DshCompositionOptions, DshCordisConfig } from './protocol.js';

type JsExpression = { readonly expression: string };
const js = (expression: string): JsExpression => ({ expression });

const DSH_PRESET_AGENT_ROWS = [
  'tool-bash',
  'tool-pwsh',
  'tool-jobs',
  'tool-fs',
  'tool-fs-search',
  'tool-str-replace-editor',
  'skill-filesystem',
  'tool-skill',
  'tool-goal',
  'plan-mode',
  'compaction-basic',
  'command-compact',
  'tool-result-pruner',
  'tool-subagent-control',
  'tool-subagent-list-agents',
  'tool-subagent',
  'tool-subagent-fork',
  'workflow-worker-thread',
  'tool-workflow',
  'tool-ralph',
  'agent-instructions',
  'tool-todo',
  'tool-web',
] as const;

/**
 * Builds Cindy's overlay over the DSH-owned base bundle. Secrets stay in env;
 * DSH owns the sandbox, approval stack, tools, and per-session preset graph.
 */
export function buildDshCordisConfig(options: DshCompositionOptions): DshCordisConfig {
  if (options.provider !== 'deepseek-official') throw new Error(`dsh only supports provider deepseek-official (got ${options.provider})`);
  if (options.apiKeyEnv !== 'DEEPSEEK_API_KEY') throw new Error('dsh deepseek adapter requires DEEPSEEK_API_KEY');
  const reasoningEffort = options.thinkingPolicy ? undefined : (options.reasoningEffort ?? 'max');
  const thinking = options.thinkingPolicy === 'always-on'
    ? 'enabled'
    : options.thinkingPolicy === 'always-off' || reasoningEffort === 'off'
      ? 'disabled'
      : 'enabled';
  const deepseekConfig = {
    ...(options.baseUrl?.trim() ? { baseURL: options.baseUrl.trim() } : {}),
    thinking,
    ...(reasoningEffort ? { reasoningEffort } : {}),
    ...(options.models?.length
      ? {
          models: options.models.map((model) => ({
            id: model.id,
            ...(model.name?.trim() ? { name: model.name.trim() } : {}),
            ...(typeof model.contextWindow === 'number' && model.contextWindow > 0
              ? { contextWindow: model.contextWindow }
              : {}),
            ...(typeof model.maxTokens === 'number' && model.maxTokens > 0
              ? { maxTokens: model.maxTokens }
              : {}),
          })),
        }
      : {}),
  };
  const config: unknown[] = [
    { id: 'hmr', disabled: true },
    { id: 'session-telemetry-otel', disabled: true },
    { id: 'session-title-llm', disabled: true },
    {
      id: 'agent-default-model',
      config: { provider: options.provider, model: options.model },
    },
    { id: 'llm-deepseek', config: deepseekConfig },
    {
      id: 'session-persistence-jsonl',
      config: {
        root: js("process.env.DSH_SESSION_ROOT ?? './.sessions'"),
        compression: js("process.env.DSH_SNAPSHOT === undefined ? 'zstd' : 'none'"),
      },
    },
    {
      id: 'sandbox-policy',
      config: {
        mode: 'workspace-write',
        workspaceRoot: js('process.env.DSH_CWD ?? process.cwd()'),
      },
    },
    { id: 'approval', config: { policy: 'ask' } },
    ...DSH_PRESET_AGENT_ROWS.map((id) => ({ id, disabled: true })),
    {
      insert: [
        { id: 'code-runtime', name: '@deepseek-ai/dsh-code-runtime-worker-thread' },
        {
          id: 'agent-presets',
          name: '@deepseek-ai/dsh-agent-presets',
        },
        { id: 'cindy-dsh-bridge', name: './cindy-dsh-bridge.mjs' },
      ],
    },
  ];
  // DshCordisConfig's index signature models individual YAML nodes; the root is a list.
  return config as unknown as DshCordisConfig;
}

/** Minimal serializer for the dsh config subset; `!!js` expressions remain executable YAML tags. */
export function renderDshCordisYaml(config: DshCordisConfig): string {
  if (!Array.isArray(config)) throw new Error('dsh cordis config must be a plugin list');
  const render = (value: unknown, depth: number): string[] => {
    const pad = '  '.repeat(depth);
    if (Array.isArray(value)) return value.flatMap((item) => {
      if (isScalar(item)) return [`${pad}- ${scalar(item)}`];
      const entries = Object.entries(item as Record<string, unknown>);
      if (!entries.length) return [`${pad}- {}`];
      const [first, ...rest] = entries;
      return [`${pad}- ${first[0]}: ${isScalar(first[1]) ? scalar(first[1]) : ''}`, ...(isScalar(first[1]) ? [] : render(first[1], depth + 2)), ...rest.flatMap(([key, child]) => isScalar(child) ? [`${pad}  ${key}: ${scalar(child)}`] : [`${pad}  ${key}:`, ...render(child, depth + 2)])];
    });
    return Object.entries(value as Record<string, unknown>).flatMap(([key, child]) => isScalar(child) ? [`${pad}${key}: ${scalar(child)}`] : [`${pad}${key}:`, ...render(child, depth + 1)]);
  };
  return ['# Generated by Cindy for the dsh JSON-RPC runtime.', '# stdout is reserved for JSON-RPC; do not add a console logger or terminal UI.', ...render(config, 0), ''].join('\n');
}
function isJs(value: unknown): value is JsExpression { return typeof value === 'object' && value !== null && 'expression' in value; }
function isScalar(value: unknown): boolean { return value === null || ['string', 'number', 'boolean'].includes(typeof value) || isJs(value); }
function scalar(value: unknown): string {
  // YAML parses `:` and `?` in an unquoted expression as structure, not code.
  if (isJs(value)) return `!!js ${JSON.stringify(value.expression)}`;
  if (value === null) return 'null'; if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  // Package names beginning with `@` are YAML reserved indicators, so the
  // renderer must not emit any string as a plain scalar. JSON string syntax is
  // valid YAML and also protects future plugin ids from YAML's other implicit
  // scalar conversions.
  return JSON.stringify(String(value));
}
